/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Controle;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.negocio.Hospital;
import modelo.negocio.Profissao;
import modelo.negocio.Profissional;
import modelo.negocio.util.Utilidade;
import modelo.negocio.util.UtilidadesData;

/**
 *
 * @author WELLITON
 */
public class CadastraProfissional extends javax.swing.JDialog {

    Controle controle = new Controle();
    UtilidadesData ud = new UtilidadesData();
    private String formato = UtilidadesData.DATA_DD_MM_YYYY;
    // private String formato = "dd/MM/yyyy";
    private int idprofissional = -1;

    /**
     * Creates new form FormSetor
     */
    public CadastraProfissional(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public CadastraProfissional(java.awt.Frame parent, boolean modal, int id) throws ParseException {
        super(parent, modal);
        initComponents();
        preencheTela(id);
        idprofissional = id;


    }

    private boolean verificarCampos() {

        String sErro = "";
        boolean erro = false;

        if (jTextFieldNome.getText().equals("")) {
            sErro = "O nome não pode ficar em branco!";
            jTextFieldNome.grabFocus();
            erro = true;
        }
        else if (jTextFieldDtnascimento.getText().equals("")) {
            sErro = "A data de nascimento nao pode ficar em branco!";
            jTextFieldDtnascimento.grabFocus();
            erro = true;
        }else if (!ud.ehDataValida(jTextFieldDtnascimento.getText(), UtilidadesData.DATA_DD_MM_YYYY)) {
            sErro = "Data invalida!";
            jTextFieldDtnascimento.grabFocus();
            erro = true;
        }
        
        if (erro) {
            JOptionPane.showMessageDialog(null, sErro, "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldConselho = new javax.swing.JTextField();
        jRadioButtonAdm = new javax.swing.JRadioButton();
        jRadioButtonUsuSistema = new javax.swing.JRadioButton();
        jRadioButtonProfissionalSaude = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jPasswordFieldConfirmaSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDtnascimento = new javax.swing.JTextField();
        jComboBoxHospital = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jComboBoxProfissao = new javax.swing.JComboBox();

        buttonGroupTipo.add(jRadioButtonAdm);
        buttonGroupTipo.add(jRadioButtonProfissionalSaude);
        buttonGroupTipo.add(jRadioButtonUsuSistema);

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        jLabel3.setText("Telefone");

        jLabel4.setText("Endereço");

        jLabel5.setText("Email");

        jLabel6.setText("Usuario");

        jLabel7.setText("Senha");

        jLabel8.setText("Conselho");

        jRadioButtonAdm.setText("Administrador");

        jRadioButtonUsuSistema.setText("Usuario Sistema");

        jRadioButtonProfissionalSaude.setText("Profissioonal de Saúde ");

        jLabel9.setText("Confirmar Senha");

        jLabel10.setText("Hospital");

        jLabel11.setText("Profissião");

        jLabel12.setText("Data de Nascimento");

        jComboBoxHospital.setModel(new DefaultComboBoxModel (controle.getHospital()));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar)
                .addGap(32, 32, 32)
                .addComponent(jButtonLimpar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonLimpar))
                .addContainerGap())
        );

        jComboBoxProfissao.setModel(new DefaultComboBoxModel (controle.getProfissao()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCpf)
                                    .addComponent(jTextFieldTelefone)
                                    .addComponent(jTextFieldConselho)
                                    .addComponent(jComboBoxHospital, 0, 133, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jRadioButtonAdm))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPasswordFieldConfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addComponent(jTextFieldDtnascimento)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonUsuSistema)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonProfissionalSaude)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                                .addComponent(jLabel7)))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addComponent(jTextFieldUsuario)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 60, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 384, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonAdm)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldDtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldConselho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonUsuSistema)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonProfissionalSaude))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBoxHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jPasswordFieldConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*  private void fechaJanela(String msn) {
     this.setVisible(false);
     JOptionPane.showMessageDialog(null, msn, "Informação", JOptionPane.INFORMATION_MESSAGE);

     }*/
    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        try {
            int tipo = -1;
            if (jRadioButtonAdm.isSelected()) {
                tipo = 0;
            }
            if (jRadioButtonUsuSistema.isSelected()) {
                tipo = 1;
            }
            if (jRadioButtonProfissionalSaude.isSelected()) {
                tipo = 2;
            }

            if (controle.validaData(jTextFieldDtnascimento.getText(), formato)) {
                if (verificarCampos()) {
                    try {
                        if (controle.ComparaData(jTextFieldDtnascimento.getText())) {
                            if (controle.validaCpf(jTextFieldCpf.getText())) {
                                if (jPasswordFieldSenha.getText().equals(jPasswordFieldConfirmaSenha.getText())) {
                                    //  try {
                                    // if (controle.BuscaCpf(jTextFieldCpf.getText())) {
                                
                                     String data = controle.visualizaAMD(jTextFieldDtnascimento.getText());
                                     // Date data = controle.transformaData_GregorianCalendar_to_YYYYMMDD(jTextFieldDtnascimento.getText());
                                     System.out.println(data);
                                     Profissional p = new Profissional(idprofissional, jTextFieldNome.getText(), jTextFieldUsuario.getText(), Utilidade.criptografa_md5(jPasswordFieldSenha.getText()), data, jTextFieldCpf.getText(), jTextFieldEndereco.getText(), jTextFieldTelefone.getText(), jTextFieldConselho.getText(), jTextFieldEmail.getText(), tipo,
                                     (Hospital) jComboBoxHospital.getSelectedItem(), (Profissao) jComboBoxProfissao.getSelectedItem());
                                     
                                    //ud.getDataGregorianCalendar();
                                    //      Profissional p = new Profissional(idprofissional, jTextFieldNome.getText(), jTextFieldUsuario.getText(), Utilidade.criptografa_md5(jPasswordFieldSenha.getText()), ud.getDataGregorianCalendar(), jTextFieldCpf.getText(), jTextFieldEndereco.getText(), jTextFieldTelefone.getText(), jTextFieldConselho.getText(), jTextFieldEmail.getText(), tipo,
                                    //        (Hospital) jComboBoxHospital.getSelectedItem(), (Profissao) jComboBoxProfissao.getSelectedItem());


                                  //  Profissional p = new Profissional(idprofissional, jTextFieldNome.getText(), jTextFieldUsuario.getText(), Utilidade.criptografa_md5(jPasswordFieldSenha.getText()), ud.getDataGregorianCalendar(), jTextFieldCpf.getText(), jTextFieldEndereco.getText(), jTextFieldTelefone.getText(), jTextFieldConselho.getText(), tipo, (Hospital) jComboBoxHospital.getSelectedItem(), (Profissao) jComboBoxProfissao.getSelectedItem(), jTextFieldTelefone.getText());
                                    String msn = null;

                                    String cpf = jTextFieldCpf.getText();
                                    if (idprofissional == -1) {
                                        if (controle.BuscaCpf(cpf)) {

                                            //controle.cadastraProfissional(p);
                                            controle.cadastraProfissional(p);

                                            msn = "Pessoa cadastrada com sucesso";

                                        } else {
                                            JOptionPane.showMessageDialog(null, "Usuario Já Possui CPF cadastrado", "Erro de validação", JOptionPane.ERROR_MESSAGE);
                                        }
                                    } else {
                                        controle.atualizaProfissional(p);
                                        msn = "Pessoa atualizada com sucesso";
                                        //    idprofissional = -1;
                                    }
                                    fechaJanela(msn);

                                    // idprofissional = -1;
                                /*     }
                                     else {
                                     JOptionPane.showMessageDialog(null, "Usuario Já Possui CPF cadastrado", "Erro de validação", JOptionPane.ERROR_MESSAGE);
                                    

                                     } catch (SQLException ex) {
                                     Logger.getLogger(CadastraProfissional.class.getName()).log(Level.SEVERE, null, ex);
                                     }*/

                                } else {
                                    JOptionPane.showMessageDialog(null, "Senha Não Confimada", "Erro de validação", JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "CPF invalido", "Erro de validação", JOptionPane.ERROR_MESSAGE);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Data de Nascimento Maior que data Atual", "Erro de validação", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(CadastraProfissional.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                System.out.println("Não validou");
                JOptionPane.showMessageDialog(null, "Data invalida", "Erro de validação", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ParseException ex) {
            Logger.getLogger(CadastraProfissional.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparTela();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimparActionPerformed
    private void preencheTela(int id) throws ParseException {

        Profissional p = controle.getProfissionalId(id);
        jTextFieldNome.setText(p.getNome());
        jTextFieldUsuario.setText(p.getUsuario());
        //  jPasswordFieldSenha.setText(p.getSenha());
        //  jPasswordFieldConfirmaSenha.setText(p.getSenha());
        jTextFieldDtnascimento.setText(controle.visualizaDMA(p.getDtNascimento()));
      //  jTextFieldDtnascimento.setText(UtilidadesData.transformaData_GregorianCalendar_to_DDMMYYYY(p.getDataNascimento()));
        jTextFieldCpf.setText(p.getCpf());
        jTextFieldTelefone.setText(p.getTelefone());
        jTextFieldConselho.setText(p.getNoConcelho());
        jTextFieldEmail.setText(p.getEmail());
        jTextFieldEndereco.setText(p.getEndereco());
        if (p.getTipo() == 0) {
            jRadioButtonAdm.setSelected(true);
        }
        if (p.getTipo() == 1) {
            jRadioButtonUsuSistema.setSelected(true);
        }
        if (p.getTipo() == 2) {
            jRadioButtonProfissionalSaude.setSelected(true);
        }
        // int tam = jComboBoxHospital.getModel().getSize();
        /*
         for (int i = 0; i < tam; i++) {
         if (((Profissional) jComboBoxHospital.getModel().getElementAt(i)).getId_profissional() == p.getHospital().getId_hospital()) {
         jComboBoxHospital.setSelectedIndex(i);
         break;
         }
         }
         for (int i = 0; i < tam; i++) {
         if (((Profissional) jComboBoxProfissao.getModel().getElementAt(i)).getId_profissional() == p.getProfissao().getId_profissao()) {
         jComboBoxProfissao.setSelectedIndex(i);
         break;
         }
         }*/
        jButtonCadastrar.setText("Atualizar");
    }

    private void limparTela() {
        jTextFieldNome.setText("");
        jTextFieldUsuario.setText("");
        //  jPasswordFieldSenha.setText(p.getSenha());
        //  jPasswordFieldConfirmaSenha.setText(p.getSenha());
        jTextFieldDtnascimento.setText("");
        jTextFieldCpf.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldConselho.setText("");
        jTextFieldEmail.setText("");
        jTextFieldEndereco.setText("");

    }

    private void fechaJanela(String msn) {
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, msn, "Informação", JOptionPane.INFORMATION_MESSAGE);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //   new CadastraProfissional().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox jComboBoxHospital;
    private javax.swing.JComboBox jComboBoxProfissao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldConfirmaSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JRadioButton jRadioButtonAdm;
    private javax.swing.JRadioButton jRadioButtonProfissionalSaude;
    private javax.swing.JRadioButton jRadioButtonUsuSistema;
    private javax.swing.JTextField jTextFieldConselho;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldDtnascimento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
