/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modelo.bd.PacienteDao;
import modelo.bd.ProfissionalDao;
import modelo.bd.ProntuarioDao;
import modelo.negocio.Paciente;
import modelo.negocio.Profissional;
import modelo.negocio.Prontuario;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lay and Lary
 */
public class CadastraProntuario extends javax.swing.JDialog {

    /**
     * Creates new form CadastraProntuario
     */
    
    ProntuarioDao prontuarioDao = new ProntuarioDao();
    PacienteDao pacienteDao = new PacienteDao();
    ProfissionalDao profissionalDao = new ProfissionalDao();
    private int idProntuario = -1;
    
    public CadastraProntuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
     public CadastraProntuario(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        preencheTela(id);
        idProntuario = id;
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcProfissional = new javax.swing.JComboBox();
        btInserir = new javax.swing.JButton();
        jcPaciente = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Paciente");

        jLabel2.setText("Profissional");

        jcProfissional.setModel((new DefaultComboBoxModel( profissionalDao.getProfissionais())));

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        jcPaciente.setModel(new javax.swing.DefaultComboBoxModel(pacienteDao.getPacientes()));
        jcPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jcProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jcPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btInserir)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btInserir)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        // TODO add your handling code here:
        
         
       
     Prontuario p = new Prontuario(idProntuario,
                        (Profissional)jcProfissional.getSelectedItem(),
                        (Paciente)jcPaciente.getSelectedItem()
                        );
             
                        String msn;
                  
        if (idProntuario == -1){ 
                prontuarioDao.cadastraProntuario(p);
                msn = "Prontuario cadastrado com sucesso";
        }
        else {
                prontuarioDao.atualizaSetor(p);
                msn = "Prontuario atualizado com sucesso";
                System.out.println(p);
        }
        fechaJanela(msn);
    }
                                        
    
    
    private void preencheTela(int id){
        
  Prontuario p = prontuarioDao.getProntuario(id);
      
       
        int tam = jcProfissional.getModel().getSize();
        for (int i = 0; i < tam; i++)
                if (((Profissional)jcProfissional.getModel().getElementAt(i)).getId_profissional() == p.getProfissional().getId_profissional()) {
                        jcProfissional.setSelectedIndex(i);
                        break;
                }
        
       int ta;
        ta = jcPaciente.getModel().getSize();
        for (int i = 0; i < ta; i++)
                if (((Paciente)jcPaciente.getModel().getElementAt(i)).getId() == p.getPaciente().getId()) {
                        jcPaciente.setSelectedIndex(i);
                        break;
                }


       
        btInserir.setText("Atualizar");
    }
    
    
    private void fechaJanela(String msn){
            this.setVisible(false);
            JOptionPane.showMessageDialog(null,msn,"Informação",JOptionPane.INFORMATION_MESSAGE);
            
    
   // TODO add your handling code here:
                                            

    }//GEN-LAST:event_btInserirActionPerformed

    private void jcPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastraProntuario dialog = new CadastraProntuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox jcPaciente;
    private javax.swing.JComboBox jcProfissional;
    // End of variables declaration//GEN-END:variables
}
