/*
 *
 * Created on 21 de Abril de 2010, 16:59
 */
package visao;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.bd.AreaDao;
import modelo.bd.BDMySql;
import modelo.bd.DoencaDao;
import modelo.negocio.Area;
import modelo.negocio.Doenca;


/**
 *
 * @author  usuario
 */
public class FormDoenca extends javax.swing.JDialog {

    BDMySql bd = BDMySql.getInstance();
    DoencaDao dd = new DoencaDao();
    AreaDao areaDao =  new AreaDao();
    int idDoenca = -1;

    /** Creates new form FormPessoa */
    public FormDoenca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    

    public FormDoenca(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        preencheTela(id);
        idDoenca = id;

    }
    public void inicializaCampos(){
        jbInserir.setText("Inserir");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jcbArea = new javax.swing.JComboBox();
        jbInserir = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Nome");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Area");
        jLabel4.setName("jLabel4"); // NOI18N

        jtfNome.setName("jtfNome"); // NOI18N

        jcbArea.setModel(new DefaultComboBoxModel (areaDao.getAreas()));
        jcbArea.setName("jcbArea"); // NOI18N
        jcbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAreaActionPerformed(evt);
            }
        });

        jbInserir.setText("Inserir");
        jbInserir.setName("jbInserir"); // NOI18N
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.setName("jbLimpar"); // NOI18N
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setText("Cadastro Doenca");
        jLabel2.setName("jLabel2"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jbInserir)
                        .add(32, 32, 32)
                        .add(jbLimpar))
                    .add(jcbArea, 0, 310, Short.MAX_VALUE))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtfNome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtfNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(47, 47, 47)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jcbArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(50, 50, 50)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbLimpar)
                    .add(jbInserir))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
    limparTela();

}//GEN-LAST:event_jbLimparActionPerformed

private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
    if (verificarCampos()) {

        Doenca d = new Doenca(idDoenca,
                jtfNome.getText(),
                (Area) jcbArea.getSelectedItem());
        String msn;
        if (idDoenca == -1) {
            dd.cadastraDoenca(d);
            msn = "Cadastro realizado com sucesso";
        } else {
            dd.atualizaDoenca(d);
            msn = "Atualizado com sucesso";
        }
        limparTela();
        fechaJanela(msn);
    }
    idDoenca = -1;
}//GEN-LAST:event_jbInserirActionPerformed

private void jcbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAreaActionPerformed
   carregaComboArea();

}//GEN-LAST:event_jcbAreaActionPerformed

    private void carregaComboArea() {

        jcbArea.removeAll();
        Vector listaAreas = areaDao.getAreas();
        for (int i = 0; i < listaAreas.size(); i++) {
            jcbArea.addItem(listaAreas.get(i));
        }
    }


    private void limparTela() {
        jtfNome.setText("");
        //jrbNone.setSelected(true);      
        jcbArea.setSelectedIndex(0);
        jtfNome.grabFocus();//coloca o focus no campo
    }

    private boolean verificarCampos() {
        String sErro = "";
        boolean erro = false;
        if (jtfNome.getText().equals("")) {
            sErro = "O nome não pode ficar em branco!";
            jtfNome.grabFocus();
            erro = true;
        }

        if (erro) {
            JOptionPane.showMessageDialog(null, sErro, "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }

    private void preencheTela(int id) {
        Doenca d = dd.getDoenca(id);
        jtfNome.setText(d.getNome());

         jbInserir.setText("Atualizar");
    }

    private void fechaJanela(String msn) {
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, msn, "Informação", JOptionPane.INFORMATION_MESSAGE);

    }
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    FormPessoa dialog = new FormPessoa(new javax.swing.JFrame(), true);
    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    public void windowClosing(java.awt.event.WindowEvent e) {
    System.exit(0);
    }
    });


    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox jcbArea;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
