/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPaciente.java
 *
 * Created on 03/03/2013, 11:44:15
 */
package visao;

import java.lang.String;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.bd.PacienteDao;
//import modelo.negocio.UtilidadesData;
import modelo.negocio.Paciente;
import modelo.negocio.util.Utilidades;
import modelo.negocio.util.UtilidadesData;
import modelo.negocio.util.Valida;

/**
 *
 * @author casa
 */
public class FormPaciente extends javax.swing.JDialog {

    PacienteDao pd = new PacienteDao();
    private int idPaciente = -1;
    UtilidadesData ud = new UtilidadesData();
    Utilidades ut = new Utilidades();
    Valida validacao = new Valida();

    /** Creates new form FormPessoa */
    public FormPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jrbInvisivel.setVisible(false);
    }

    public FormPaciente(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        this.jrbInvisivel.setVisible(false);
        preencheTela(id);
        idPaciente = id;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelPaciente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlSexo = new javax.swing.JLabel();
        jrbFeminino = new javax.swing.JRadioButton();
        jrbMasculino = new javax.swing.JRadioButton();
        jrbInvisivel = new javax.swing.JRadioButton();
        jlEndereco = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jlRg = new javax.swing.JLabel();
        jtfRg = new javax.swing.JFormattedTextField();
        jlCpf = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JFormattedTextField();
        jlDataNasc = new javax.swing.JLabel();
        jtfDataNasc = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        btInserir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabelPaciente.setName("jLabelPaciente"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabelPaciente)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setName("jPanel2"); // NOI18N

        jlNome.setName("jlNome"); // NOI18N

        jtfNome.setName("jtfNome"); // NOI18N

        jlSexo.setName("jlSexo"); // NOI18N

        buttonGroup1.add(jrbFeminino);
        jrbFeminino.setName("jrbFeminino"); // NOI18N

        buttonGroup1.add(jrbMasculino);
        jrbMasculino.setSelected(true);
        jrbMasculino.setName("jrbMasculino"); // NOI18N

        buttonGroup1.add(jrbInvisivel);
        jrbInvisivel.setEnabled(false);
        jrbInvisivel.setName("jrbInvisivel"); // NOI18N

        jlEndereco.setName("jlEndereco"); // NOI18N

        jtfEndereco.setName("jtfEndereco"); // NOI18N

        jlTelefone.setName("jlTelefone"); // NOI18N

        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setName("jtfTelefone"); // NOI18N

        jlRg.setName("jlRg"); // NOI18N

        try {
            jtfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfRg.setName("jtfRg"); // NOI18N

        jlCpf.setName("jlCpf"); // NOI18N

        try {
            jtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCpf.setName("jtfCpf"); // NOI18N

        jlDataNasc.setName("jlDataNasc"); // NOI18N

        try {
            jtfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataNasc.setName("jtfDataNasc"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlRg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlCpf))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlDataNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jrbMasculino)
                                        .addGap(14, 14, 14)
                                        .addComponent(jrbFeminino))
                                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEndereco)
                            .addComponent(jlSexo))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jrbInvisivel))
                            .addComponent(jtfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexo)
                    .addComponent(jrbInvisivel)
                    .addComponent(jrbMasculino)
                    .addComponent(jrbFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlEndereco)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefone)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRg)
                    .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpf)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataNasc)
                    .addComponent(jtfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setName("jPanel3"); // NOI18N

        btInserir.setName("btInserir"); // NOI18N
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btLimpar.setName("btLimpar"); // NOI18N
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btInserir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        String dataNasc = "";
        String tel = jtfTelefone.getText();
        String rg = jtfRg.getText();
        String cpf1 = jtfCpf.getText();
        jtfTelefone.getText();

        if (verificarCampos()) {
            Paciente p = new Paciente(idPaciente,
                    jtfNome.getText(),
                    jrbMasculino.isSelected() ? 'M' : 'F',
                    jtfEndereco.getText(),
                    ut.removerCaracterEspecial(tel),
                    ut.removerCaracterEspecial(rg),
                    ud.getDataGregorianCalendar(),
                    ut.removerCaracterEspecial(cpf1));

            String msn;
            if (idPaciente == -1) {
                pd.cadastraPaciente(p);
                msn = "Paciente cadastrado com sucesso";
            } else {
                pd.atualizaPaciente(p);
                msn = "Paciente atualizado com sucesso";
            }
            limparTela();
            fechaJanela(msn);
        }

    }//GEN-LAST:event_btInserirActionPerformed

    private void limparTela() {
        jtfNome.setText("");
        jrbInvisivel.setSelected(true);
        jrbMasculino.setSelected(false);
        jrbFeminino.setSelected(false);
        jtfEndereco.setText("");
        jtfTelefone.setText("");
        jtfRg.setText("");
        jtfCpf.setText("");
        jtfDataNasc.setText("");
        jtfNome.grabFocus();//coloca o focus no campo
    }

    private boolean verificarCampos() {

        String sErro = "";
        boolean erro = false;

        if (jtfNome.getText().equals("")) {
            sErro = "O nome não pode ficar em branco!";
            jtfNome.grabFocus();
            erro = true;
        } else if (!jrbMasculino.isSelected() && !jrbFeminino.isSelected()) {
            sErro = "Selecione o sexo!";
            jrbMasculino.grabFocus();
            erro = true;
        } else if (jtfEndereco.getText().equals("")) {
            sErro = "O endereco nao pode ficar em branco!";
            jtfEndereco.grabFocus();
            erro = true;
        } else if (jtfTelefone.getText().equals("")) {
            sErro = "O telefone nao pode ficar em branco!";
            jtfTelefone.grabFocus();
            erro = true;
        } else if (jtfRg.getText().equals("")) {
            sErro = "O RG nao pode ficar em branco!";
            jtfRg.grabFocus();
            erro = true;

        } else if (jtfCpf.getText().equals("")) {
            sErro = "O cpf nao pode ficar em branco!";
            jtfCpf.grabFocus();
            erro = true;

        } else if (!validacao.validarCPF(jtfCpf.getText())) {
            sErro = "CPF invalido!";
            jtfCpf.grabFocus();
            erro = true;
        } else if (jtfDataNasc.getText().equals("")) {
            sErro = "A data de nascimento nao pode ficar em branco!";
            jtfDataNasc.grabFocus();
            erro = true;
        } else if (!ud.ehDataValida(jtfDataNasc.getText(), UtilidadesData.DATA_DD_MM_YYYY)) {
            sErro = "Data invalida!";
            jtfDataNasc.grabFocus();
            erro = true;
        }
        if (erro) {
            JOptionPane.showMessageDialog(null, sErro, "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }

    private void preencheTela(int id) {
        Paciente p = pd.getPaciente(id);
        jtfNome.setText(p.getNome());
        if (p.getSexo() == 'M') {
            jrbMasculino.setSelected(true);
        } else {
            jrbFeminino.setSelected(true);
        }
        jtfEndereco.setText(p.getEndereco());
        jtfTelefone.setText(p.getTelefone());
        jtfRg.setText(p.getRg());
        //jtfDataNasc.setText(UtilidadesData.transformaData_GregorianCalendar_to_DDMMYYYY(p.getDataNasc()));
        jtfCpf.setText(p.getCpf());


        btInserir.setText("Atualizar");
    }

    private void fechaJanela(String msn) {
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, msn, "Informação", JOptionPane.INFORMATION_MESSAGE);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                FormPaciente dialog = new FormPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);

                    }
                });
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlDataNasc;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JRadioButton jrbFeminino;
    private javax.swing.JRadioButton jrbInvisivel;
    private javax.swing.JRadioButton jrbMasculino;
    private javax.swing.JFormattedTextField jtfCpf;
    private javax.swing.JFormattedTextField jtfDataNasc;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JFormattedTextField jtfRg;
    private javax.swing.JFormattedTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
