/*
 * TelaProfissao.java
 *
 * Created on 3 de Março de 2013, 17:46
 */
package visao;

import modelo.bd.BDMySql;
import modelo.bd.FichaDao;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author  Jessica
 */
public class TelaFichaPrincipal extends javax.swing.JFrame {

    FichaDao fichaDao = new FichaDao();
    BDMySql bd = BDMySql.getInstance();
    private JDialog telaFicha;


    public TelaFichaPrincipal() {
        initComponents();
        //atualizaTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaAvaliacao = new javax.swing.JTable();
        btInserir = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtListaAvaliacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrição", "Área"
            }
        ));
        jScrollPane1.setViewportView(jtListaAvaliacao);

        btInserir.setFont(new java.awt.Font("Tahoma", 1, 11));
        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 11));
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11));
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11));
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btInserir)
                        .addGap(23, 23, 23)
                        .addComponent(btAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)
                        .addGap(28, 28, 28)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir)
                    .addComponent(btSair)
                    .addComponent(btExcluir)
                    .addComponent(btAtualizar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        if (telaFicha == null) {
            //JFrame mainFrame = TelaPrincipal.getApplication().getMainFrame();
            telaFicha = new TelaFicha(this, true);
            telaFicha.setLocationRelativeTo(this);
        }
        telaFicha.setVisible(true);
        atualizaTabela();
                                           
    
    }//GEN-LAST:event_btInserirActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        int i = jtListaAvaliacao.getSelectedRow();

        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            int id = Integer.parseInt((String) jtListaAvaliacao.getValueAt(i, 0));

            telaFicha = new TelaFicha(this, true, id);
            telaFicha.setLocationRelativeTo(this);
            telaFicha.setVisible(true);
            atualizaTabela();
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Object[] options = {"Confirmar", "Cancelar"};
        int m = JOptionPane.showOptionDialog(null,
                "Deseja realmente exluir o registro selecionado?", "Informação",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                null, options, options[0]);
        if (m == 0) {
            int i = jtListaAvaliacao.getSelectedRow();
            if (i == -1) {
                JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                int id = Integer.parseInt((String) jtListaAvaliacao.getValueAt(i, 0));
                fichaDao.deletaFicha(id);
                JOptionPane.showMessageDialog(null, "Registro excluído com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
                atualizaTabela();

            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TelaFichaPrincipal t = new TelaFichaPrincipal();
                t.setTitle("Sistema de Avaliação do Pacientes");
                t.atualizaTabela();
                t.setVisible(true);
            }
        });
    }

    public void atualizaTabela() {
        Object[][] lista = fichaDao.listaFicha();
        jtListaAvaliacao.setModel(new javax.swing.table.DefaultTableModel(
                lista, new String[]{"ID", "Nome","Área","Descrição"}) {
        });
        jtListaAvaliacao.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtListaAvaliacao.getColumnModel().getColumn(0).setResizable(true);
        jtListaAvaliacao.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtListaAvaliacao.getColumnModel().getColumn(1).setResizable(true);
        jtListaAvaliacao.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtListaAvaliacao.getColumnModel().getColumn(1).setResizable(true);
        jtListaAvaliacao.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtListaAvaliacao.getColumnModel().getColumn(1).setResizable(true);


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtListaAvaliacao;
    // End of variables declaration//GEN-END:variables
}
