/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormSetor.java
 *
 * Created on 10/02/2013, 13:55:40
 */
package visao;

import modelo.bd.BDMySql;
import modelo.bd.FichaDao;
import modelo.negocio.FichaAvaliacao;
import javax.swing.JOptionPane;

/**
 *
 * @author casa
 */
public class TelaFicha extends javax.swing.JDialog {

    FichaDao fichaDao = new FichaDao();
    BDMySql bd = BDMySql.getInstance();
    private int idFicha = -1;

    /** Creates new form FormSetor */
    public TelaFicha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public TelaFicha(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        preencheTela(id);
        idFicha = id;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonInserir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabelNome.setFont(new java.awt.Font("Monotype Corsiva", 1, 18));
        jLabelNome.setText("Nome");
        jLabelNome.setName("jLabelNome"); // NOI18N

        jTextNome.setName("jTextNome"); // NOI18N

        jLabelDescricao.setFont(new java.awt.Font("Monotype Corsiva", 1, 18));
        jLabelDescricao.setText("Descrição");
        jLabelDescricao.setName("jLabelDescricao"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jTextAreaDescricao.setName("jTextAreaDescricao"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jButtonInserir.setText("Inserir");
        jButtonInserir.setName("jButtonInserir"); // NOI18N
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setName("jButtonLimpar"); // NOI18N
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel1.setText("Ficha de avaliação");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButtonInserir)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescricao)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addGap(18, 18, 18)
                                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonInserir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        if (verificarCampos()) {

            FichaAvaliacao ficha = new FichaAvaliacao(idFicha,
                    jTextNome.getText(),
                    jTextAreaDescricao.getText());

            String msn;
            if (idFicha == -1) {
                fichaDao.cadastraFicha(ficha);
                msn = "Ficha cadastrado com sucesso";
            } else {
                fichaDao.atualizaFicha(ficha);
                msn = "Ficha atualizado com sucesso";
            }
            limparTela();
            fechaJanela(msn);
        }
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void limparTela() {
        jTextNome.setText("");
        jTextAreaDescricao.setText("");
        jTextNome.grabFocus();//coloca o focus no campo
    }

    private boolean verificarCampos() {
        String sErro = "";
        boolean erro = false;
        if (jTextNome.getText().equals("")) {
            sErro = "O nome não pode ficar em branco!";
            jTextNome.grabFocus();
            erro = true;
        }else
        if (jTextAreaDescricao.getText().equals("")) {
            sErro = "A descrição não pode ficar em branco!";
            jTextNome.grabFocus();
            erro = true;
        }
        if (erro) {
            JOptionPane.showMessageDialog(null, sErro, "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }

    private void preencheTela(int id) {
        FichaAvaliacao f = fichaDao.getFicha(id);
        jTextNome.setText(f.getNome());
        jTextAreaDescricao.setText(f.getDescricao());
        jButtonInserir.setText("Atualizar");


    }

    private void fechaJanela(String msn) {
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, msn, "Informação", JOptionPane.INFORMATION_MESSAGE);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
}
