/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormSetor.java
 *
 * Created on 10/02/2013, 13:55:40
 */
package visao;

import controle.ControleAvaliacao;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import modelo.bd.BDMySql;
import modelo.bd.FichaDao;
import modelo.negocio.FichaAvaliacao;
import javax.swing.JOptionPane;
import modelo.bd.AreaDao;
import modelo.negocio.Area;

/**
 *
 * @author casa
 */
public class TelaFicha extends javax.swing.JDialog {

    FichaDao fichaDao = new FichaDao();
    ControleAvaliacao controle = new ControleAvaliacao();
    AreaDao areaDao = new AreaDao();
    BDMySql bd = BDMySql.getInstance();
    private int idFicha = -1;

    /** Creates new form FormSetor */
    public TelaFicha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public TelaFicha(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        preencheTela(id);
        idFicha = id;

    }

   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jbtInserir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlArea = new javax.swing.JLabel();
        jcArea = new javax.swing.JComboBox();

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 18));
        jLabelNome.setText("Nome");
        jLabelNome.setName("jLabelNome"); // NOI18N

        jTextNome.setName("jTextNome"); // NOI18N

        jLabelDescricao.setFont(new java.awt.Font("Arial", 1, 18));
        jLabelDescricao.setText("Descrição");
        jLabelDescricao.setName("jLabelDescricao"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jTextAreaDescricao.setName("jTextAreaDescricao"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jbtInserir.setFont(new java.awt.Font("Tahoma", 1, 11));
        jbtInserir.setText("Inserir");
        jbtInserir.setName("jbtInserir"); // NOI18N
        jbtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInserirActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setName("jButtonLimpar"); // NOI18N
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setText("Ficha de avaliação");
        jLabel1.setName("jLabel1"); // NOI18N

        jlArea.setFont(new java.awt.Font("Arial", 1, 18));
        jlArea.setText("Área");
        jlArea.setName("jlArea"); // NOI18N

        jcArea.setModel(new DefaultComboBoxModel (areaDao.getAreas()));
        jcArea.setName("jcArea"); // NOI18N
        jcArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtInserir)
                                .addGap(46, 46, 46)
                                .addComponent(jButtonLimpar))
                            .addComponent(jcArea, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlArea)
                    .addComponent(jcArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtInserir)
                    .addComponent(jButtonLimpar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInserirActionPerformed
       if (verificarCampos()) {

            FichaAvaliacao f = new FichaAvaliacao(
                    idFicha,jTextNome.getText(),
                    jTextAreaDescricao.getText(),
                    (Area) jcArea.getSelectedItem());
                    
            String msn;
            
            if (idFicha == -1) {
                fichaDao.cadastraFicha(f);
                msn = "Ficha cadastrado com sucesso";
            } else {
                fichaDao.atualizaFicha(f);
                msn = "Ficha atualizado com sucesso";
            }
            limparTela();
            fechaJanela(msn);
        }
    }//GEN-LAST:event_jbtInserirActionPerformed

    private void carregaComboFicha() {
        jcArea.removeAll();
        Vector listaAreas = areaDao.getAreas();
        for (int i = 0; i < listaAreas.size(); i++) {
            jcArea.addItem(listaAreas.get(i));
        }
    }
    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jcAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAreaActionPerformed
        carregaComboFicha();
                // TODO add your handling code here:
    }//GEN-LAST:event_jcAreaActionPerformed

    private void limparTela() {
        jTextNome.setText("");
        jTextAreaDescricao.setText("");
        jTextNome.grabFocus();//coloca o focus no campo
    }

    private boolean verificarCampos() {
        String sErro = "";
        boolean erro = false;
        if (jTextNome.getText().equals("")) {
            sErro = "O nome não pode ficar em branco!";
            jTextNome.grabFocus();
            erro = true;
        }else
        if (jTextAreaDescricao.getText().equals("")) {
            sErro = "A descrição não pode ficar em branco!";
            jTextNome.grabFocus();
            erro = true;
        }
        if (erro) {
            JOptionPane.showMessageDialog(null, sErro, "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }

    private void preencheTela(int id) {

        FichaAvaliacao f = fichaDao.getFicha(id);
        jTextNome.setText(f.getNome());
        jTextAreaDescricao.setText(f.getDescricao());
        //jbtInserir.setText("Atualizar");

    }


    private void fechaJanela(String msn) {
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, msn, "Informação", JOptionPane.INFORMATION_MESSAGE);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JButton jbtInserir;
    private javax.swing.JComboBox jcArea;
    private javax.swing.JLabel jlArea;
    // End of variables declaration//GEN-END:variables
}
