/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPaciente.java
 *
 * Created on 03/03/2013, 12:40:37
 */
package visao;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.bd.PacienteDao;
import modelo.negocio.util.Utilidades;


/**
 *
 * @author casa
 */
public class TelaPaciente extends javax.swing.JFrame {
    String caracter;
    Utilidades ut= new Utilidades();
    PacienteDao pd = new PacienteDao();
  //  private JDialog formPaciente;
     private JDialog formPaciente;

    /** Creates new form TelaPaciente */
    public TelaPaciente() {
        initComponents();
        atualizaTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaPacientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbInserir = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTableListaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Sexo", "CPF"
            }
        ));
        jTableListaPacientes.setName("jTableListaPacientes"); // NOI18N
        jScrollPane1.setViewportView(jTableListaPacientes);

        jPanel1.setName("jPanel1"); // NOI18N

        jbInserir.setName("jbInserir"); // NOI18N
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAtualizar.setName("jbAtualizar"); // NOI18N
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbExcluir.setName("jbExcluir"); // NOI18N
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSair.setName("jbSair"); // NOI18N
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        int i = jTableListaPacientes.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            int id = Integer.parseInt((String) jTableListaPacientes.getValueAt(i, 0));

            formPaciente = new FormPaciente(this, true, id);
            formPaciente.setLocationRelativeTo(this);
            formPaciente.setVisible(true);
            atualizaTabela();
        }
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Object[] options = {"Confirmar", "Cancelar"};
        int m = JOptionPane.showOptionDialog(null,
                "Deseja realmente exluir o registro selecionado?", "Informação",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                null, options, options[0]);
        if (m == 0) {
            int i = jTableListaPacientes.getSelectedRow();
            if (i == -1) {
                JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                int id = Integer.parseInt((String) jTableListaPacientes.getValueAt(i, 0));
                pd.deletaPaciente(id);
                JOptionPane.showMessageDialog(null, "Registro excluído com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
                atualizaTabela();
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        if ( formPaciente == null) {
            //JFrame mainFrame = TelaPrincipal.getApplication().getMainFrame();
            formPaciente = new  FormPaciente(this, true);
            formPaciente.setLocationRelativeTo(this);
        }
        formPaciente.setVisible(true);
        //limpar os campos aqui
        atualizaTabela();
    }//GEN-LAST:event_jbInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TelaPaciente tp = new TelaPaciente();
                tp.setTitle("Sistema de controle de clinica medica");
                tp.atualizaTabela();
                tp.setVisible(true);

            }        });
    }

    private void atualizaTabela() {
        Object[][] lista = pd.listaPacientes();
        jTableListaPacientes.setModel(new javax.swing.table.DefaultTableModel(
                lista, new String[]{"id", "Nome", "Sexo", "CPF"}) {
        });
        jTableListaPacientes.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableListaPacientes.getColumnModel().getColumn(0).setResizable(true);
        jTableListaPacientes.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableListaPacientes.getColumnModel().getColumn(1).setResizable(true);
        jTableListaPacientes.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTableListaPacientes.getColumnModel().getColumn(2).setResizable(true);
        jTableListaPacientes.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTableListaPacientes.getColumnModel().getColumn(3).setResizable(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaPacientes;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbSair;
    // End of variables declaration//GEN-END:variables

    
}
