/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modelo.negocio.Atendimento;
import javax.swing.JDialog;
import modelo.bd.AtendimentoDao;
import modelo.bd.BDMySql;
import javax.swing.JOptionPane;

/**
 *
 * @author Lay and Lary
 */
public class TelaAtendimento extends javax.swing.JFrame {
AtendimentoDao atendimentoDao = new AtendimentoDao();
    BDMySql bd  = BDMySql.getInstance();
    private JDialog formAtendimento;
    /**
     * Creates new form TelaAtendimento
     */
    public TelaAtendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaAtendimentos = new javax.swing.JTable();
        jbInserir = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtListaAtendimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Horario", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaAtendimentos);

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbInserir)
                .addGap(18, 18, 18)
                .addComponent(jbAtualizar)
                .addGap(18, 18, 18)
                .addComponent(jbExcluir)
                .addGap(32, 32, 32)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInserir)
                    .addComponent(jbAtualizar)
                    .addComponent(jbExcluir)
                    .addComponent(jbSair))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed

        if (formAtendimento == null) {
            //JFrame mainFrame = TelaPrincipal.getApplication().getMainFrame();
            formAtendimento = new CadastraAtendimento(this, true);
            formAtendimento.setLocationRelativeTo(this);
        }
       formAtendimento = new CadastraAtendimento(this, true);
      formAtendimento.setVisible(true);
        atualizaTabela();
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed

        int i = jtListaAtendimentos.getSelectedRow();

        if (i == -1) JOptionPane.showMessageDialog(null,"Selecione uma linha da tabela","Erro",JOptionPane.ERROR_MESSAGE);
        else {
            int  id = Integer.parseInt((String)jtListaAtendimentos.getValueAt(i, 0));

           formAtendimento = new CadastraAtendimento(this, true,id);
           formAtendimento.setLocationRelativeTo(this);
            formAtendimento.setVisible(true);
            atualizaTabela();
        }
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Object[] options = { "Confirmar", "Cancelar" };
        int m = JOptionPane.showOptionDialog(null,
            "Deseja realmente exluir o registro selecionado?", "Informação",
            JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
            null, options, options[0]);
        if (m == 0) {
            int i = jtListaAtendimentos.getSelectedRow();
            if (i == -1) JOptionPane.showMessageDialog(null,"Selecione uma linha da tabela","Erro",JOptionPane.ERROR_MESSAGE);
            else {
                int  id = Integer.parseInt((String)jtListaAtendimentos.getValueAt(i, 0));
                atendimentoDao.deletaPessoa(id);
                JOptionPane.showMessageDialog(null,"Registro excluído com sucesso","Informação",JOptionPane.INFORMATION_MESSAGE);
                atualizaTabela();

            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        //this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAtendimento at = new TelaAtendimento();
                at.setTitle("Sistema de controle de Atendimentos");
                at.atualizaTabela();
               at.setVisible(true);
            }
        });
    }
    
    public void atualizaTabela(){
		Object[][] lista = atendimentoDao.listaAtendimentos();
		jtListaAtendimentos.setModel(new javax.swing.table.DefaultTableModel(
				lista, new String[] { "id", "Data", "Horario",	"descricao","Prontuario"}) {
			
		});
		jtListaAtendimentos.getColumnModel().getColumn(0).setPreferredWidth(50);
		jtListaAtendimentos.getColumnModel().getColumn(0).setResizable(true);
		jtListaAtendimentos.getColumnModel().getColumn(1).setPreferredWidth(150);
		jtListaAtendimentos.getColumnModel().getColumn(1).setResizable(true);
		jtListaAtendimentos.getColumnModel().getColumn(2).setPreferredWidth(60);
		jtListaAtendimentos.getColumnModel().getColumn(2).setResizable(true);
		jtListaAtendimentos.getColumnModel().getColumn(3).setPreferredWidth(160);
		jtListaAtendimentos.getColumnModel().getColumn(3).setResizable(true);
                jtListaAtendimentos.getColumnModel().getColumn(3).setPreferredWidth(160);
		jtListaAtendimentos.getColumnModel().getColumn(3).setResizable(true);

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbSair;
    private javax.swing.JTable jtListaAtendimentos;
    // End of variables declaration//GEN-END:variables
}
