/*
 * TelaPrincipal.java
 *
 
 */

package visao;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.bd.BDMySql;
import modelo.bd.DoencaDao;


/**
 *
 * @author  Renato Novais
 */
public class TelaDoenca extends javax.swing.JFrame {

    
    BDMySql bd  = BDMySql.getInstance();
    DoencaDao dd = new DoencaDao();
    private JDialog formDoenca;
    
    
    /** Creates new form TelaPrincipal */
    public TelaDoenca() {
        initComponents();
        atualizaTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbInserir = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbInserir23 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaDoenca = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setName("jPanel2"); // NOI18N

        jbInserir.setText("Inserir");
        jbInserir.setName("jbInserir"); // NOI18N
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar");
        jbAtualizar.setName("jbAtualizar"); // NOI18N
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setName("jbExcluir"); // NOI18N
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.setName("jbSair"); // NOI18N
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbInserir23.setText("Inserir");
        jbInserir23.setName("jbInserir23"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jbInserir)
                .add(18, 18, 18)
                .add(jbAtualizar)
                .add(18, 18, 18)
                .add(jbExcluir)
                .add(32, 32, 32)
                .add(jbSair, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1202, 1202, 1202)
                .add(jbInserir23)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbInserir23)
                    .add(jbInserir)
                    .add(jbAtualizar)
                    .add(jbExcluir)
                    .add(jbSair))
                .addContainerGap())
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtListaDoenca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Area"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaDoenca.setName("jtListaDoenca"); // NOI18N
        jScrollPane1.setViewportView(jtListaDoenca);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("Iniciar");
        jMenu1.setName("jMenu1"); // NOI18N

        jMenuItem1.setText("Sair");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ferramentas");
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");
        jMenu3.setName("jMenu3"); // NOI18N

        jMenuItem2.setText("Sobre");
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, 0, 404, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 404, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
    int i = jtListaDoenca.getSelectedRow();
    if (i == -1) JOptionPane.showMessageDialog(null,"Selecione uma linha da tabela","Erro",JOptionPane.ERROR_MESSAGE);
    else {
            int  id = Integer.parseInt((String)jtListaDoenca.getValueAt(i, 0));
            
            formDoenca= new FormDoenca(this, true, id);
            formDoenca.setLocationRelativeTo(this);
            formDoenca.setVisible(true);
            atualizaTabela();
    }
}//GEN-LAST:event_jbAtualizarActionPerformed

private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
    Object[] options = { "Confirmar", "Cancelar" };
    int m = JOptionPane.showOptionDialog(null,
                    "Deseja realmente exluir o registro selecionado?", "Informação",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                    null, options, options[0]);
    if (m == 0) {
            int i = jtListaDoenca.getSelectedRow();
            if (i == -1) JOptionPane.showMessageDialog(null,"Selecione uma linha da tabela","Erro",JOptionPane.ERROR_MESSAGE);
            else {
                    int  id = Integer.parseInt((String)jtListaDoenca.getValueAt(i, 0));
                    dd.deletaDoenca(id);
                    JOptionPane.showMessageDialog(null,"Registro excluído com sucesso","Informação",JOptionPane.INFORMATION_MESSAGE);
                    atualizaTabela();

            }
    }
}//GEN-LAST:event_jbExcluirActionPerformed

private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
    System.exit(0);
}//GEN-LAST:event_jbSairActionPerformed

private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed

    if (formDoenca == null) {
        //JFrame mainFrame = TelaPrincipal.getApplication().getMainFrame();
        formDoenca = new FormDoenca(this, true);
        formDoenca.setLocationRelativeTo(this);
    }
     formDoenca.setVisible(true);
    atualizaTabela();
}//GEN-LAST:event_jbInserirActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    jbSairActionPerformed(evt);
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    JOptionPane.showMessageDialog(null, "Aplicação Java \n"
                                + "desenvolvida por\n" + "Alunos Licenciatura em Computação"
                                + "IFBA Campus Santo Amaro 2012.2", "Sobre",
                                JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDoenca t = new TelaDoenca();
                t.setTitle("Sistema de controle de Clínica");
                t.atualizaTabela();
                t.setVisible(true);
            }
        });
    }
    
    
    public void atualizaTabela(){
		Object[][] lista = dd.listaDoenca();
		jtListaDoenca.setModel(new javax.swing.table.DefaultTableModel(
				lista, new String[] { "id", "Nome", "Area"}) {
			
		});
		jtListaDoenca.getColumnModel().getColumn(0).setPreferredWidth(50);
		jtListaDoenca.getColumnModel().getColumn(0).setResizable(true);
		jtListaDoenca.getColumnModel().getColumn(1).setPreferredWidth(150);
		jtListaDoenca.getColumnModel().getColumn(1).setResizable(true);
		jtListaDoenca.getColumnModel().getColumn(2).setPreferredWidth(60);
		jtListaDoenca.getColumnModel().getColumn(2).setResizable(true);
		
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbInserir23;
    private javax.swing.JButton jbSair;
    private javax.swing.JTable jtListaDoenca;
    // End of variables declaration//GEN-END:variables

}
