/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaProntuario.java
 *
 * Created on 23/03/2013, 09:01:17
 */

package visao;

import modelo.bd.ProntuarioDao;

/**
 *
 * @author labinfo
 */
public class TelaProntuario extends javax.swing.JFrame {


    ProntuarioDao prontuarioDao = new ProntuarioDao();

    /** Creates new form TelaProntuario */
    public TelaProntuario() {
        initComponents();
    }


    public void atualizaTabela(){
		Object[][] lista = prontuarioDao.listaProntuario();
		jtListaProntuarios.setModel(new javax.swing.table.DefaultTableModel(
				lista, new String[] { "id", "Paciente", "Profissional"}) {

		});
		jtListaProntuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
		jtListaProntuarios.getColumnModel().getColumn(0).setResizable(true);
		jtListaProntuarios.getColumnModel().getColumn(1).setPreferredWidth(150);
		jtListaProntuarios.getColumnModel().getColumn(1).setResizable(true);
		jtListaProntuarios.getColumnModel().getColumn(2).setPreferredWidth(60);
		jtListaProntuarios.getColumnModel().getColumn(2).setResizable(true);
		

	}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaProntuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtListaProntuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Horario", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaProntuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaProntuario at = new TelaProntuario();
                at.setTitle("Sistema de controle de Prontuarios");
                at.atualizaTabela();
               at.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtListaProntuarios;
    // End of variables declaration//GEN-END:variables

}
